services:
  web:
    container_name: web
    image: nginx
    ports:
      - "80:80"
    networks:
      - test
    profiles:
      - completo
    depends_on:
      - php
  php:
    container_name: php
    build:
      context: .
      dockerfile: php.Dockerfile
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - test
    profiles:
      - completo
    depends_on:
      - db
  bd:
    container_name: mysql
    image: mysql:8.3
    profiles:
      - completo
      - bd

networks:
  test: